### ISSUE TITLE
template from url

### ISSUE THREAD

**Issue by wiyatnanto** [stone-payments/kong-plugin-template-transformer#114]
how to use a template from a url, I tried to use a template on a separate url but it doesn't work well, please help

**Comment by jonathanlazaro1** [comment]
Hi, @wiyatnanto  ! Sorry for the (**really**) late response. Even not knowing if you still will benefit from it, I will answer your question, so at least it can serve as a reference for people having the same need in the future.

Currently what you mentioned is not possible (it's kind of related with #151 ). I believe it wouldn't be practical to support this, considering that:
* If we are just fetching the template contents from the URL instead of passing those contents as a configuration field, like it's done today, it doesn't really sound that useful (with the "bonus" of potentially adding HTTP-related issues). Also, you can easily achieve this by fetching those contents from the URL by yourself, before configure your routes the way you are used to do
* if the aim is to establish some sort of "dynamic templating", adding this extra fetching time to every request sound like a thing most APIs wouldn't want to have (and neither their clients). Also, I would say it goes fundamentally against what most API designs are made for (strong request/response contracts). Of course, you can have a specific scenario where it does make sense, but I believe would be specific enough to not be supported at plugin side.

Since a lot of time had passed, I will go ahead and close this issue. Feel free to contact me if you have further questions.

**Comment by wiyatnanto** [comment]
thank you @jonathanlazaro1  for the reply. I quite understand what you mean. thank you this plugin is very useful
