### ISSUE TITLE
Compatibility with kong 2.x

### ISSUE THREAD

**Issue by hsibia** [stone-payments/kong-plugin-template-transformer#127]
### Issue Description
Getting error when enabling KONG_STREAM_LISTEN in Kong 2.x. 
nginx: [error] init_by_lua error: /usr/local/share/lua/5.1/kong/tools/utils.lua:625: error loading module 'kong.plugins.kong-plugin-template-transformer.handler':
/usr/local/share/lua/5.1/resty/template.lua:147: attempt to index field 'location' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/resty/template.lua:147: in main chunk
	[C]: in function 'require'
	...ong-plugin-template-transformer/template_transformer.lua:1: in main chunk
	[C]: in function 'require'
	...ong/plugins/kong-plugin-template-transformer/handler.lua:20: in main chunk
	[C]: at 0x7f6e985f40f0
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:616: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:483: in function 'init'
	init_by_lua:11: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/local/share/lua/5.1/kong/tools/utils.lua:625: in function 'load_module_if_exists'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:149: in function 'load_plugin_handler'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:227: in function 'load_plugin'
	/usr/local/share/lua/5.1/kong/db/dao/plugins.lua:275: in function 'load_plugin_schemas'
	/usr/local/share/lua/5.1/kong/init.lua:483: in function 'init'
	init_by_lua:11: in main chunk

**Comment by jonathanlazaro1** [comment]
Hi, @hsibia ! A lot of time has passed since you opened this issue (and for that I sincerely apologize). The good news is that this plugin now is compatible with kong 2.x. Better late than never, I guess? :sweat_smile: 

The last published version (`v1.0.1`) was built and tested using kong `v2.6`, but I had no problem using it with kong `v2.8`, too.

Since a lot of time had passed, I will go ahead and close this issue. Feel free to contact me if you have further questions.
