### ISSUE TITLE
how to use a template from a file?

### ISSUE THREAD

**Issue by nandrianakos** [stone-payments/kong-plugin-template-transformer#151]
how to use a template from a file, as /home/foo/api_xxx/req_transformer.lua 

![Screenshot 2022-03-09 100632](https://user-images.githubusercontent.com/18256889/157398956-e896bead-d967-4b3e-8ca6-2abf52d588b2.png)

req_transformer.lua file:
{ 	
	"Id": {{body.MarketInstanceIds[1]}},
        "SampleString": "{{body.TestString}}"
}

please help

**Comment by nandrianakos** [comment]
Could anyone help, please?

**Comment by nandrianakos** [comment]
Any help, please?

**Comment by jonathanlazaro1** [comment]
Hi, @nandrianakos ! Sorry for the (**really**) late response. Even not knowing if you still will benefit from it, I will answer your question, so at least it can serve as a reference for people having the same need in the future.

Unfortunately, it is not possible to pass a file reference directly to the plugin configuration. This is likely not-doable, as we aim to let the plugin be used in containerized scenarios, where manage those file references would potentially be tricky.

A workaround could be something like this:
* Establishing a standard for your request/response template files (that would be plain text files, containing your transformations). These files must be named in a concise way to match your kong routes
* Processing these file references during kong configuration phase (e.g. while creating your Docker image or deploying). You could have a Python script making POST requests to Admin API, in order to configure the plugin in a route-by-route manner, or a step that would parse these files contents to a `yaml` file, if using declarative/db-less mode in kong.

Although this is a little tedious, since it must be made route-by-route, I think it will be justified by the long term benefits (especially if you have a lot of routes using template transformation).

Since a lot of time had passed, I will go ahead and close this issue. Feel free to contact me if you want more information, or even a PoC on how to do the above said.
